import { useState } from 'react'
import { motion } from 'framer-motion'
import { useQuizStore } from '../store/quizStore'

const EXAMPLE = `{
  "title": "JLPT N5 Vocabulary",
  "topic": "Genki I · Chapter 3",
  "questions": [
    {
      "question": "What does this mean?",
      "jp": "たべる",
      "choices": ["to drink", "to eat", "to sleep"],
      "correct": 1
    }
  ]
}`

export default function ImportModal({ onClose }) {
  const addQuiz = useQuizStore((s) => s.addQuiz)
  const [text, setText] = useState('')
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)

  const handleImport = () => {
    setError('')
    try {
      const data = JSON.parse(text.trim())
      if (!data.title || !Array.isArray(data.questions) || data.questions.length === 0) {
        throw new Error('Missing title or questions array')
      }
      for (const q of data.questions) {
        if (!q.question || !Array.isArray(q.choices) || q.choices.length < 2) {
          throw new Error('Each question needs "question", "choices" array, and "correct" index')
        }
        if (typeof q.correct !== 'number') {
          throw new Error('"correct" must be a number (0-indexed)')
        }
      }
      addQuiz(data)
      setSuccess(true)
      setTimeout(onClose, 800)
    } catch (e) {
      setError(e.message)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, zIndex: 200,
        background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(4px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24,
      }}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        onClick={(e) => e.stopPropagation()}
        style={{
          background: 'var(--surface)',
          border: '1px solid var(--border-bright)',
          borderRadius: 'var(--radius)',
          padding: 32,
          width: '100%', maxWidth: 560,
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: 'linear-gradient(90deg, var(--pink), var(--yellow))' }} />

        <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 28, letterSpacing: 1, marginBottom: 4 }}>
          Import New Quiz
        </div>
        <div style={{ fontSize: 13, color: 'var(--muted)', marginBottom: 20 }}>
          Paste JSON generated by Claude below. Format:
        </div>

        <pre style={{
          background: 'var(--surface2)', border: '1px solid var(--border)',
          borderRadius: 8, padding: 14, fontSize: 11,
          color: 'var(--muted)', overflowX: 'auto', marginBottom: 16,
          fontFamily: 'monospace', lineHeight: 1.5,
        }}>
          {EXAMPLE}
        </pre>

        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Paste quiz JSON here..."
          style={{
            width: '100%', height: 160,
            background: 'var(--surface2)', border: `1px solid ${error ? 'var(--red)' : 'var(--border-md)'}`,
            borderRadius: 8, padding: 14, color: 'var(--text)', fontSize: 13,
            resize: 'vertical', fontFamily: 'monospace', lineHeight: 1.5,
          }}
        />

        {error && (
          <div style={{ color: 'var(--red)', fontSize: 12, marginTop: 8 }}>
            ✗ {error}
          </div>
        )}
        {success && (
          <div style={{ color: 'var(--green)', fontSize: 13, marginTop: 8 }}>
            ✓ Quiz imported successfully!
          </div>
        )}

        <div style={{ display: 'flex', gap: 10, marginTop: 20, justifyContent: 'flex-end' }}>
          <button className="btn btn-ghost" onClick={onClose}>Cancel</button>
          <button className="btn btn-primary" onClick={handleImport} disabled={!text.trim()}>
            Import Quiz
          </button>
        </div>
      </motion.div>
    </motion.div>
  )
}
